### ISSUE TITLE
An error has occured in one of your routes: Host is unreachable

### ISSUE THREAD

**Issue by HaveANiceDay21** [sekai-soft/guide-nitter-self-hosting#12]
I setup everything properly and it gives me this error when I search up a user:

```
An error has occured in one of your routes.

Detail: asyncfutures.nim(389) read
asyncfutures.nim(389) read
asyncfutures.nim(389) read
asyncfutures.nim(389) read
asyncfutures.nim(389) read
asyncfutures.nim(389) read
http_pool.nim(49) fetchRawIter
apiutils.nim(121) fetchRawIter
apiutils.nim(127) fetchRawIter
??? fetchRawIter
asyncfutures.nim(389) read
asyncfutures.nim(389) read
redpool.nim(68) getUserIdIter
asyncfutures.nim(389) read
asyncfutures.nim(389) read
asyncfutures.nim(389) read
asyncfutures.nim(389) read
asyncfutures.nim(389) read
Host is unreachable
```

Also how can I disable the password login thing?

**Comment by KTachibanaM** [comment]
`Host is unreachable` looks like a temporary networking issue. Have you tried restarting the docker compose stack? What environment are you running the stack in? Does other nitter features work?

You can disable password protection by adding `DISABLE_NGINX=1` to the `nitter` service's `environment`, and changing `ports` to `"0.0.0.0:8080:8080"` (they are both in the `docker-compose.nitter.yml` file). But beaware that if you are hosting it in a public VPS, you need to make sure you've setup proper firewall/rate-limiting yourself.

**Comment by HaveANiceDay21** [comment]
I fixed the problem, but it gives me this now:
```
An error has occured in one of your routes.

Detail: oserr.nim(95) raiseOSError
asyncfutures.nim(389) read
asyncfutures.nim(389) read
asyncfutures.nim(389) read
asyncfutures.nim(389) read
asyncfutures.nim(389) read
http_pool.nim(49) fetchIter
apiutils.nim(121) fetchIter
apiutils.nim(127) fetchIter
??? fetchIter
asyncfutures.nim(389) read
asyncfutures.nim(389) read
asyncfutures.nim(389) read
asyncfutures.nim(389) read
asyncfutures.nim(389) read
asyncfutures.nim(389) read
Invalid argument
Additional info: Try again
```

**Comment by KTachibanaM** [comment]
I tried to search nitter code for the error but couldn't find anything that resembles this. Perhaps you should restart the stack again or change for another burner account.
