### ISSUE TITLE
https - howto?

### ISSUE THREAD

**Issue by ghta01** [sekai-soft/guide-nitter-self-hosting#15]
I have "https = true" set in my nitter.conf, and "NITTER_HTTPS=true" set in my .env, but links are still generated as http://, instead of https:// -- is there something i've missed to get this to work?

thanks

**Comment by KTachibanaM** [comment]
Added an environment variable `INSTANCE_HTTPS=1` that would add `https = true` in the nitter config https://github.com/sekai-soft/nitter/commit/962b6eb39acd8641625530414cb271c4bb4c589d
