### ISSUE TITLE
2FA PIN required while attempting to deploy on Fly.io

### ISSUE THREAD

**Issue by duartebranco** [sekai-soft/guide-nitter-self-hosting#16]
I attempted to deploy the application on Fly.io, but encountered a problem with Twitter authentication. When attempting to log in, the login process is flagged as "suspicious" (probably because of the different country), and Twitter sends a PIN to my email (even though 2FA isn't enabled). And the application can't log into my twitter, so it does not deploy properly.

**Comment by KTachibanaM** [comment]
Related to https://github.com/sekai-soft/guide-nitter-self-hosting/issues/14
