### ISSUE TITLE
No Items found when searching on my Nitter Instance

### ISSUE THREAD

**Issue by jesuspb2** [sekai-soft/guide-nitter-self-hosting#19]
<img width="954" alt="Captura de pantalla 2024-08-04 a las 13 06 51" src="https://github.com/user-attachments/assets/a9fec782-aed4-46ad-b305-5de3c2e8c61d">

Have you experienced this? I changed the twitter account creating a new one but still have the issue "No items found"

**Comment by KTachibanaM** [comment]
I was able to find items with the "elon" keyword. Perhaps some logs would be helpful to debug the issue (likely rate limited because the search endpoint was abused heavily when public nitter instances were still alive).

**Comment by AritzUMA** [comment]
It is working perfect for me, the only problem is that I get rate limited fast. Can we add more than one account?

**Comment by KTachibanaM** [comment]
Looks like you opened https://github.com/sekai-soft/guide-nitter-self-hosting/issues/22 so going to close this one :)
