### ISSUE TITLE
Multiple twitter accounts

### ISSUE THREAD

**Issue by AritzUMA** [sekai-soft/guide-nitter-self-hosting#22]
Hi eryone,

First of all thanks to @sekai-soft for this proyect, it works perfectly for me. The only think that I miss, is to know if is possible use multiple account instead of only one.

Thanks for all

**Comment by KTachibanaM** [comment]
Add this feature https://github.com/sekai-soft/guide-nitter-self-hosting/blob/master/docs/guide.md#multiple-twitter-accounts

**Comment by AritzUMA** [comment]
I works perfectly!!!! Thankssss
