### ISSUE TITLE
Failed authentication

### ISSUE THREAD

**Issue by A-LAM-3** [sekai-soft/guide-nitter-self-hosting#23]
Getting this error when trying to start Nitter now:

`Failed authentication. You might have entered the wrong username/password. Please rerun with environment variable DEBUG=1 for debugging.`

**Comment by KTachibanaM** [comment]
Updated repo and it should be fixed.

**Comment by A-LAM-3** [comment]
That seemed to fix it! Thanks so much!

**Comment by A-LAM-3** [comment]
RSS feeds seem to no longer pull images now – not sure if that's fixable though..
