### ISSUE TITLE
Videos dont have audio

### ISSUE THREAD

**Issue by 2Epik4u** [sekai-soft/guide-nitter-self-hosting#26]
![image](https://github.com/user-attachments/assets/ed68ef28-e6de-4038-a929-7ee883ad2ed6)
![image](https://github.com/user-attachments/assets/dad22235-f2ca-4dea-93e0-25d8925c8b35)

When hovering over a video, you cannot unmute the video and its stuck muted, and you also cant download the video.

[docker-compose.yml](https://github.com/user-attachments/files/17927380/docker-compose.txt)
[nitter.conf](https://github.com/user-attachments/files/17927399/nitter.txt)
here is both of my config files, hopefully theres a way to fix it.

**Comment by ojaha065** [comment]
I had the exact same issue but enabling `USE_CUSTOM_CONF=1` and then setting `proxyVideos` to `false` and `hlsPlayback` to `true` in nitter.conf fixed it for me. But according to the files you provided you already have that so I dunno why it isn't working for you :shrug:

The values provided in nitter.conf are only the default values. Did you check you haven't overridden them via the settings page in the UI?
![Nitter settings](https://github.com/user-attachments/assets/7247f900-9085-44c5-bba8-8adc4064def0)

**Comment by KTachibanaM** [comment]
Yeah the default configuration seems to have the same problem for me and I don't know how to fix it yet. I'll make the default as @ojaha065 suggested for now
